services:
  - type: web
    name: genesis-sa-services
    runtime: python
    buildCommand: pip install -r requirements-render.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_SECRET_KEY
        value: render_deployment_secure_key_2025
      - key: OPENAI_API_KEY
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: RENDER
        value: "true"
    plan: free
    autoDeploy: true
