services:
  - type: web
    name: genesis-sa-services
    env: python
    buildCommand: chmod +x ./build.sh ./render_start.sh && ./build.sh && ./render_start.sh
    startCommand: gunicorn app:app
    envVars:
      - fromFile: .env.render
